language: ruby
notifications:
  email: false
  slack:
    secure: lzu9tidqyeTV7+xtAy5rU08fa8fm6mx4bVaKCebSw5gZyBEi37D3n8qGdvhxHBJq81/yLpxnqagoByYRYqUTHBlG0inq5X3wKOxTYNUROBBsK1kNPNmSeICj50Cb/PdykkqN88QL6YCJBklYnef/ecrKNO/+6E0pp6xneE5EUdaIk/vx7Rvh6oac3CabcRwftkFAi3iXbm8N6a0Qh0d/izz9O+kradDMQJGhKwYtCRZzFLP5WiOABiZjeqVuGRMV71TSxWPfLUMBDxQ/Cn8BOPZ6GiHydLF9UJG9G2nX08UNGKd3BO47QOUCXwpK8+10iP+CWIIpEL2HfAPJkfj7Jafgo6aQsnwDhxwfzMxvEBOD4lWlx4aEEy7lA3NoDrLigOpmc0Ijda+FEYNLSBrqCPuB7ELwkjkJTTxH9sEPSDZ0sh/f+gDafMs/TMd2SJ2Nu5ybXB8EipoAbZKmsGN1/C44/RO2xdcZuyxtyKnS6LIG3nF87H36QcTQTiEI2kEZ5R6UFqN9uwnHiDIDBBSoR6F5XKh8ALniV6sTT3LDeg3WBxcNw+TNpDJKeKpmbiE6k/Hz0bG4xQtSirjLY5RjON5IpML6Cx0TWnmqKg6GUx9KNvXCEji4mbqAmRM1ivzb+2DpDfdXkzZwvgqG5J553Mx/RMHwEZyrN8D4BhzD00A=
cache: bundler
rvm:
  - 2.4.0
before_script:
  - bundle exec rails db:create db:migrate
script:
  - bundle exec rails tests
deploy:
  provider: heroku
  app:
    master: photo-schmoto
  run:
    - bundle exec rails db:migrate
  api_key:
    secure: s2Kefeb+t5p0Zy99/p2YseHJOyi5aYDIP/hQQgTCQltRKv2K1KyFb4RDYv2i5fr+Vx4RYm7qS+BqNVxNNb9q4W0Lo+tE+vs3BrRbNUGpqSTe1aS7MbOhXjQIuB1sVo8j8omgibHLqAPBUYJ5X2WVEyfJqMQiMfKvFbboil3rI/Q/Bp/7gtJaYl7CRJGL7vaCvqMIkcRF2G57b5+8QKq56nCzDK32+svELTdwqzGD9YMu54piCDrlftLAPn53qJr2GUMhVvPlobqo63097c7Safnf0MXXDREGNQllw2tyCGb+qqRK9J5JRb19f3gCqTpGMdxZSDFYSQLSOzkxXGRTpL2JdbNrnh5TLgNTGGxjN4XwtEKyPirJ8F0dLjEZkQclga+z+ZjwcLbShy9rQDnhdXqQPoI5UmHeGnt6RE7M+iVJMdIbsTsW6fHwjTMMTeK+iISZJRF3abp+8yY/0Zg944HrxMxdNReCtVpwV0t/UHYz3IAJOPVCXhf5N6O3Tc2T44xa1rgiQWOX4Gq8L8iXYqGa5J3NduahTZqhRlEPdV22vQMbEnu4QUtuNYXNlJlOzyW2XYw/4hVnRNytYtr5zd4vNYKmYwqgYqBOfzM5OGlOmCut5u92PTSaPymo4ZNuQTzH1xKUlsoBWEiWzuAfG27DsmE2Qc95NTXWb/l6VxM=
