# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f5e328d3b052f0c390ca2a366aad12f25aa27755a237d60be34bfbc3b4a9955318f147446fba2d1995ad7e3f1fcc9998a7fc3c254433956d3195329bb1688216

test:
  secret_key_base: 8f1ca517353f3bbf7ec04e85587725b8332d6923a88cc1265a3b5681fd8392f2513652cb72fd9270b053f648a8b7bcb6343617b06f7a99b266b51c524d6a9b44

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
